[package]
name = "Generative"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
image = "0.23.14"
regex = "1.5.4"
uuid = { version = "0.8", features = ["serde", "v4"] }